### ISSUE TITLE
re-start hangs on optimizing JS

### ISSUE THREAD

**Issue by alex-dizengof** [dsugden/cluster-console#6]
After running the example according to the instruction it just hangs on JS optimizations.
it is due to an issue with the sbt-scalajs plugin. In order to solve it just upgrade the plugin to 0.6.8
(I have also updated sbt to 0.13.11 for me)

B.T.W - great project!

**Comment by dsugden** [comment]
cool, thnx for this, this project isn't maintained currently, but a fork is here: https://github.com/boldradius/cluster-console

I'll update the README with this
